-- SELECT ERROR_TYPE FROM NCLK.T_NCLK_EXAMROOM_LOG_HIS GROUP BY ERROR_TYPE, EXAMROOM_ID;

-- E
-- SELECT H.ERROR_TYPE, E.EXAMROOM_ID FROM NCLK.T_NCLK_EXAMROOM_LOG_HIS H, NCLK.T_NCLK_EXAMROOM E WHERE H.EXAMROOM_ID = E.EXAMROOM_ID GROUP BY ERROR_TYPE, EXAMROOM_ID;

-- P
-- SELECT P.ENDPOINT_ID FROM NCLK.T_NCLK_EXAMROOM_LOG_HIS H, NCLK.T_NCLK_EXAMROOM E, NCLK.T_NCLK_ENDPOINT P WHERE H.EXAMROOM_ID = E.EXAMROOM_ID AND P.ENDPOINT_ID = E.ENDPOINT_ID GROUP BY H.ERROR_TYPE, E.EXAMROOM_ID;

-- A
-- SELECT H.ERROR_TYPE, A.AREA_ID FROM NCLK.T_NCLK_EXAMROOM_LOG_HIS H, NCLK.T_NCLK_EXAMROOM E, NCLK.T_NCLK_ENDPOINT P, NCLK.T_NCLK_AREA A WHERE H.EXAMROOM_ID = E.EXAMROOM_ID AND P.ENDPOINT_ID = E.ENDPOINT_ID AND P.AREA_ID = A.AREA_ID GROUP BY H.ERROR_TYPE, E.EXAMROOM_ID;

-- PA
-- SELECT H.ERROR_TYPE, B.AREA_ID FROM NCLK.T_NCLK_EXAMROOM_LOG_HIS H, NCLK.T_NCLK_EXAMROOM E, NCLK.T_NCLK_ENDPOINT P, NCLK.T_NCLK_AREA A, NCLK.T_NCLK_AREA B WHERE H.EXAMROOM_ID = E.EXAMROOM_ID AND P.ENDPOINT_ID = E.ENDPOINT_ID AND P.AREA_ID = A.AREA_ID AND A.PARENT_AREA_ID = B.AREA_ID GROUP BY H.ERROR_TYPE, E.EXAMROOM_ID;
