-- SELECT ERROR_TYPE FROM NCLK.T_NCLK_EXAMROOM_LOG_HIS H, NCLK.T_NCLK_EXAMROOM E, NCLK.T_NCLK_ENDPOINT P, NCLK.T_NCLK_AREA A, NCLK.T_NCLK_AREA B WHERE H.EXAMROOM_ID = E.EXAMROOM_ID AND E.ENDPOINT_ID = P.ENDPOINT_ID AND P.AREA_ID = A.AREA_ID AND A.PARENT_AREA_ID = B.AREA_ID;
 
-- SELECT ERROR_TYPE FROM T_NCLK_EXAMROOM_LOG_HIS GROUP BY ERROR_TYPE, EXAMROOM_ID;

SELECT ERROR_TYPE FROM NCLK.T_NCLK_EXAMROOM_LOG_HIS H, NCLK.T_NCLK_EXAMROOM E, NCLK.T_NCLK_ENDPOINT P, NCLK.T_NCLK_AREA A, NCLK.T_NCLK_AREA B, NCLK.T_NCLK_AREA C WHERE H.EXAMROOM_ID = E.EXAMROOM_ID AND E.ENDPOINT_ID = P.ENDPOINT_ID AND P.AREA_ID = A.AREA_ID AND A.PARENT_AREA_ID = B.AREA_ID AND B.PARENT_AREA_ID = C.AREA_ID AND C.AREA_ID = "19a15ed40225464ea58595e52f77b2fc" GROUP BY H.ERROR_TYPE, H.EXAMROOM_ID;