
CREATE DATABASE IF NOT EXISTS NCLK DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

USE NCLK;

/*==============================================================*/
/* Table: T_NCLK_AREA                                           */
/*==============================================================*/

DROP TABLE IF EXISTS T_NCLK_AREA;

CREATE TABLE T_NCLK_AREA (
  AREA_ID VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '区域ID',
  PARENT_AREA_ID VARCHAR(32) COLLATE utf8_bin DEFAULT NULL COMMENT '上级区域ID',
  AREA_NAME VARCHAR(50) COLLATE utf8_bin NOT NULL COMMENT '区域名称',
  AREA_TYPE CHAR(1) COLLATE utf8_bin NOT NULL COMMENT '区域类型 1:省级指挥中心 2:市级指挥中心 3:县区级指挥中心',
  CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  STATE CHAR(1) COLLATE utf8_bin NOT NULL COMMENT '状态 A:有效 X:无效',
  ORD INT(11) DEFAULT NULL COMMENT '排序号',
  PRIMARY KEY (AREA_ID)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='区域信息表';

/*==============================================================*/
/* Table: T_NCLK_ENDPOINT                                       */
/*==============================================================*/

DROP TABLE IF EXISTS T_NCLK_ENDPOINT;

CREATE TABLE T_NCLK_ENDPOINT (
  ENDPOINT_ID VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '考点ID',
  ENDPOINT_NO VARCHAR(50) COLLATE utf8_bin NOT NULL COMMENT '考点编号',
  ENDPOINT_NAME VARCHAR(50) COLLATE utf8_bin NOT NULL COMMENT '考点名称',
  ENDPOINT_ADDR VARCHAR(100) COLLATE utf8_bin DEFAULT NULL COMMENT '考点地址',
  AREA_ID VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '所属区域ID',
  ENDPOINT_PERSON VARCHAR(50) COLLATE utf8_bin DEFAULT NULL COMMENT '考点负责人',
  ENDPOINT_TEL VARCHAR(50) COLLATE utf8_bin DEFAULT NULL COMMENT '考点负责人电话',
  ENDPOINT_IP VARCHAR(20) COLLATE utf8_bin NOT NULL COMMENT '考点服务器IP',
  ENDPOINT_PORT VARCHAR(10) COLLATE utf8_bin NOT NULL COMMENT '考点服务器端口',
  CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  STATE CHAR(1) COLLATE utf8_bin NOT NULL COMMENT '状态 A:有效 X:无效',
  ORD INT(11) DEFAULT NULL COMMENT '顺序号',
  PRIMARY KEY (ENDPOINT_ID),
  KEY FK_ENDPOINT_FK_AREA_idx (AREA_ID),
  CONSTRAINT `FK_ENDPOINT_FK_AREA` FOREIGN KEY (AREA_ID) REFERENCES T_NCLK_AREA (AREA_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='考点信息表';


/*==============================================================*/
/* Table: T_NCLK_EXAMROOM                                       */
/*==============================================================*/

DROP TABLE IF EXISTS T_NCLK_EXAMROOM;

CREATE TABLE T_NCLK_EXAMROOM (
  EXAMROOM_ID VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '考场ID',
  EXAMROOM_IP VARCHAR(20) COLLATE utf8_bin NOT NULL COMMENT '考场子钟IP',
  EXAMROOM_NAME VARCHAR(50) COLLATE utf8_bin DEFAULT NULL COMMENT '考场名称',
  EXAMROOM_ADDR VARCHAR(100) COLLATE utf8_bin DEFAULT NULL COMMENT '考场地址',
  EXAMROOM_PERSON VARCHAR(50) COLLATE utf8_bin DEFAULT NULL COMMENT '考场负责人',
  EXAMROOM_TEL VARCHAR(50) COLLATE utf8_bin DEFAULT NULL COMMENT '考场负责人电话',
  ENDPOINT_ID VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '考点ID',
  CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  STATE VARCHAR(10) COLLATE utf8_bin NOT NULL DEFAULT 'normal' COMMENT '状态 normal:正常状态 error:异常状态 disable:停用状态  ',
  PRIMARY KEY (EXAMROOM_ID),
  KEY FK_EXAMROOT_FK_ENDPOINT_idx (ENDPOINT_ID),
  CONSTRAINT FK_EXAMROOT_FK_ENDPOINT FOREIGN KEY (ENDPOINT_ID) REFERENCES T_NCLK_ENDPOINT (ENDPOINT_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='考场信息表';

/*==============================================================*/
/* Table: T_NCLK_EXAMROOM_LOG                                   */
/*==============================================================*/

DROP TABLE IF EXISTS T_NCLK_EXAMROOM_LOG;

CREATE TABLE T_NCLK_EXAMROOM_LOG (
  EXAMROOM_LOG_ID VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '考场日志ID',
  EXAMROOM_ID VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '考场ID',
  ERROR_TYPE VARCHAR(50) COLLATE utf8_bin NOT NULL COMMENT '异常类型',
  ERROR_DESC VARCHAR(100) COLLATE utf8_bin NOT NULL COMMENT '异常描述',
  ERROR_DATE DATETIME NOT NULL COMMENT '异常时间',
  PRIMARY KEY (EXAMROOM_LOG_ID),
  KEY FK_EXAMROOM_LOG_FK_EXAMROOM_idx (EXAMROOM_ID),
  CONSTRAINT FK_EXAMROOM_LOG_FK_EXAMROOM FOREIGN KEY (EXAMROOM_ID) REFERENCES T_NCLK_EXAMROOM (EXAMROOM_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='考场实时日志信息表';

/*==============================================================*/
/* Table: T_NCLK_EXAMROOM_LOG_HIS                               */
/*==============================================================*/

DROP TABLE IF EXISTS `T_NCLK_EXAMROOM_LOG_HIS`;

CREATE TABLE T_NCLK_EXAMROOM_LOG_HIS (
  EXAMROOM_LOG_HIS_ID VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '考场日志ID',
  EXAMROOM_ID VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '考场ID',
  ERROR_TYPE VARCHAR(50) COLLATE utf8_bin NOT NULL COMMENT '异常类型',
  ERROR_DESC VARCHAR(100) COLLATE utf8_bin NOT NULL COMMENT '异常描述',
  ERROR_DATE DATETIME NOT NULL COMMENT '异常时间',
  PRIMARY KEY (EXAMROOM_LOG_HIS_ID),
  KEY FK_EXAMROOM_LOG_HIS_FK_EXAMROOM (EXAMROOM_ID),
  CONSTRAINT FK_EXAMROOM_LOG_HIS_FK_EXAMROOM FOREIGN KEY (EXAMROOM_ID) REFERENCES T_NCLK_EXAMROOM (EXAMROOM_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='考场历史日志信息表';

/*==============================================================*/
/* Table: T_NCLK_MODULE                                         */
/*==============================================================*/

DROP TABLE IF EXISTS T_NCLK_MODULE;

CREATE TABLE T_NCLK_MODULE (
  MODULE_ID VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '模块ID',
  PARENT_MODULE_ID VARCHAR(32) COLLATE utf8_bin DEFAULT NULL COMMENT '上级模块ID',
  MODULE_NAME VARCHAR(50) COLLATE utf8_bin NOT NULL COMMENT '模块名称',
  MODULE_URL VARCHAR(200) COLLATE utf8_bin DEFAULT NULL COMMENT '模块URL',
  MODULE_ICON VARCHAR(50) COLLATE utf8_bin DEFAULT NULL COMMENT '模块图标',
  CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  STATE CHAR(1) COLLATE utf8_bin NOT NULL COMMENT '状态 A:有效 X:无效',
  ORD INT(11) DEFAULT NULL COMMENT '排序号',
  PRIMARY KEY (MODULE_ID)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='模块信息表';


/*==============================================================*/
/* Table: T_NCLK_USER                                           */
/*==============================================================*/

DROP TABLE IF EXISTS T_NCLK_USER;

CREATE TABLE T_NCLK_USER (
  USER_ID VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '用户ID',
  NAME VARCHAR(50) COLLATE utf8_bin NOT NULL COMMENT '姓名',
  USERNAME VARCHAR(50) COLLATE utf8_bin NOT NULL COMMENT '用户名',
  PASSWORD VARCHAR(50) COLLATE utf8_bin NOT NULL COMMENT '密码',
  LOGIN_DATE DATETIME DEFAULT NULL COMMENT '最近登录时间',
  LOGIN_ERROR_COUNT INT(11) NOT NULL COMMENT '登录错误次数',
  LOCK_DATE DATETIME DEFAULT NULL COMMENT '锁定时间',
  PHOTO LONGBLOB COMMENT '照片',
  CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  STATE CHAR(1) COLLATE utf8_bin NOT NULL COMMENT '状态 A:有效 L:锁定 X:无效',
  ORD INT(11) DEFAULT NULL COMMENT '排序号',
  PRIMARY KEY (USER_ID)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='用户信息表';

/*==============================================================*/
/* Table: T_NCLK_USER_AREA                                      */
/*==============================================================*/

DROP TABLE IF EXISTS T_NCLK_USER_AREA;

CREATE TABLE T_NCLK_USER_AREA (
  USER_AREA_ID VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '用户所属区域ID',
  USER_ID VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '用户ID',
  AREA_ID VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '区域ID',
  PRIMARY KEY (USER_AREA_ID),
  KEY FK_USER_AREA_FK_USER_idx (USER_ID),
  KEY FK_USER_AREA_FK_AREA_idx (AREA_ID),
  CONSTRAINT FK_USER_AREA_FK_AREA FOREIGN KEY (AREA_ID) REFERENCES T_NCLK_AREA (AREA_ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_USER_AREA_FK_USER FOREIGN KEY (USER_ID) REFERENCES T_NCLK_USER (USER_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='用户所属区域信息表';

/*==============================================================*/
/* Table: T_NCLK_USER_AUTH                                      */
/*==============================================================*/

DROP TABLE IF EXISTS T_NCLK_USER_AUTH;

CREATE TABLE T_NCLK_USER_AUTH (
  USER_AUTH_ID VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '用户权限ID',
  USER_ID VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '用户ID',
  MODULE_ID VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '模块ID',
  PRIMARY KEY (USER_AUTH_ID),
  KEY FK_USER_AUTH_FK_USER_idx (USER_ID),
  KEY FK_USER_AUTH_FK_MODULE_idx (MODULE_ID),
  CONSTRAINT FK_USER_AUTH_FK_MODULE FOREIGN KEY (MODULE_ID) REFERENCES T_NCLK_MODULE (MODULE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_USER_AUTH_FK_USER FOREIGN KEY (USER_ID) REFERENCES T_NCLK_USER (USER_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='用户权限信息表';

/*==============================================================*/
/* Table: T_NCLK_USER_ENDPOINT                                  */
/*==============================================================*/

DROP TABLE IF EXISTS T_NCLK_USER_ENDPOINT;

CREATE TABLE T_NCLK_USER_ENDPOINT (
  USER_ENDPOINT_ID VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '用户所属考点ID',
  USER_ID VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '用户ID',
  ENDPOINT_ID VARCHAR(32) COLLATE utf8_bin NOT NULL COMMENT '考点ID',
  PRIMARY KEY (USER_ENDPOINT_ID),
  KEY FK_USER_ENDPOINT_FK_USER_idx (USER_ID),
  KEY FK_USER_ENDPOINT_FK_ENDPOINT_idx (ENDPOINT_ID),
  CONSTRAINT FK_USER_ENDPOINT_FK_ENDPOINT FOREIGN KEY (ENDPOINT_ID) REFERENCES T_NCLK_ENDPOINT (ENDPOINT_ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_USER_ENDPOINT_FK_USER FOREIGN KEY (USER_ID) REFERENCES T_NCLK_USER (USER_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='用户所属考点信息表';

