-- SELECT PARENT_AREA_ID FROM NCLK.T_NCLK_AREA where AREA_ID in ( select AREA_ID from NCLK.T_NCLK_ENDPOINT where ENDPOINT_ID in (select ENDPOINT_ID from NCLK.T_NCLK_EXAMROOM where STATE = "error" ));

-- select AREA_ID from NCLK.T_NCLK_ENDPOINT where ENDPOINT_ID in (select ENDPOINT_ID from NCLK.T_NCLK_EXAMROOM where STATE = "error" );

-- select ENDPOINT_ID,count(*) as eidCount from NCLK.T_NCLK_EXAMROOM where STATE = "error" group by ENDPOINT_ID ;

-- select ENDPOINT_ID from NCLK.T_NCLK_EXAMROOM where STATE = "error" ;

-- select AREA_ID from NCLK.T_NCLK_ENDPOINT where NCLK.T_NCLK_EXAMROOM.STATE = "error" ;

select A.PARENT_AREA_ID, P.AREA_ID, E.ENDPOINT_ID from NCLK.T_NCLK_AREA A, NCLK.T_NCLK_ENDPOINT P, NCLK.T_NCLK_EXAMROOM E where E.STATE = "error" and P.ENDPOINT_ID = E.ENDPOINT_ID and A.AREA_ID = P.AREA_ID;

-- select A.PARENT_AREA_ID from NCLK.T_NCLK_AREA A, NCLK.T_NCLK_ENDPOINT P, NCLK.T_NCLK_EXAMROOM E where E.STATE = "error" and P.ENDPOINT_ID = E.ENDPOINT_ID and A.AREA_ID = P.AREA_ID;