SELECT * FROM NCLK.T_NCLK_ENDPOINT;


SELECT B.AREA_NAME, COUNT(*) 'AREA_NUM'
FROM NCLK.T_NCLK_EXAMROOM E, NCLK.T_NCLK_ENDPOINT P, NCLK.T_NCLK_AREA A, NCLK.T_NCLK_AREA B 
WHERE E.STATE = "error" AND E.ENDPOINT_ID = P.ENDPOINT_ID AND P.AREA_ID = A.AREA_ID AND 
A.PARENT_AREA_ID = B.AREA_ID AND A.STATE = 'A' AND B.STATE = 'A' AND P.STATE = 'A' AND B.AREA_NAME = "南京市" 
GROUP BY B.AREA_NAME;

SELECT HS.ERROR_TYPE, COUNT(*) 'ERROR_NUM'
FROM (SELECT H.ERROR_TYPE
FROM NCLK.T_NCLK_EXAMROOM_LOG_HIS H, NCLK.T_NCLK_EXAMROOM E, NCLK.T_NCLK_ENDPOINT P, 
NCLK.T_NCLK_AREA A, NCLK.T_NCLK_AREA B, NCLK.T_NCLK_AREA C 
WHERE H.EXAMROOM_ID = E.EXAMROOM_ID AND E.ENDPOINT_ID = P.ENDPOINT_ID AND P.AREA_ID = A.AREA_ID 
AND A.PARENT_AREA_ID = B.AREA_ID AND B.PARENT_AREA_ID = C.AREA_ID AND C.AREA_ID = "000000032" 
GROUP BY H.ERROR_TYPE, H.EXAMROOM_ID) HS
group by HS.ERROR_TYPE;

SELECT A.AREA_NAME 'DISTRICT_NAME', COUNT(*) 'A', B.AREA_NAME 'CITY_NAME', C.AREA_NAME 'PROVINCE_NAME'
FROM NCLK.T_NCLK_EXAMROOM_LOG_HIS H, NCLK.T_NCLK_EXAMROOM E, NCLK.T_NCLK_ENDPOINT P, 
NCLK.T_NCLK_AREA A, NCLK.T_NCLK_AREA B, NCLK.T_NCLK_AREA C 
WHERE H.EXAMROOM_ID = E.EXAMROOM_ID AND E.ENDPOINT_ID = P.ENDPOINT_ID AND P.AREA_ID = A.AREA_ID 
AND A.PARENT_AREA_ID = B.AREA_ID AND B.PARENT_AREA_ID = C.AREA_ID AND C.AREA_ID = "000000032" 
GROUP BY H.ERROR_TYPE, H.EXAMROOM_ID;

SELECT HS.ENDPOINT_NAME 'DISTRICT_NAME', COUNT(*) 'DISTRICT_NUM'
FROM (SELECT P.ENDPOINT_NAME
FROM NCLK.T_NCLK_EXAMROOM_LOG_HIS H, NCLK.T_NCLK_EXAMROOM E, NCLK.T_NCLK_ENDPOINT P, 
NCLK.T_NCLK_AREA A, NCLK.T_NCLK_AREA B, NCLK.T_NCLK_AREA C
WHERE H.EXAMROOM_ID = E.EXAMROOM_ID AND E.ENDPOINT_ID = P.ENDPOINT_ID AND P.AREA_ID = A.AREA_ID 
AND A.PARENT_AREA_ID = B.AREA_ID AND B.PARENT_AREA_ID = C.AREA_ID AND A.AREA_NAME = "太仓市"
GROUP BY H.ERROR_TYPE, H.EXAMROOM_ID) HS
GROUP BY HS.ENDPOINT_NAME;

SELECT HS.AREA_NAME 'DISTRICT_NAME', COUNT(*) 'DISTRICT_NUM'
FROM (SELECT B.AREA_NAME
FROM NCLK.T_NCLK_EXAMROOM_LOG_HIS H, NCLK.T_NCLK_EXAMROOM E, NCLK.T_NCLK_ENDPOINT P, 
NCLK.T_NCLK_AREA A, NCLK.T_NCLK_AREA B, NCLK.T_NCLK_AREA C
WHERE H.EXAMROOM_ID = E.EXAMROOM_ID AND E.ENDPOINT_ID = P.ENDPOINT_ID AND P.AREA_ID = A.AREA_ID 
AND A.PARENT_AREA_ID = B.AREA_ID AND B.PARENT_AREA_ID = C.AREA_ID AND C.AREA_ID = "000000032"
GROUP BY H.ERROR_TYPE, H.EXAMROOM_ID) HS
GROUP BY HS.AREA_NAME;

SELECT HS.AREA_NAME 'DISTRICT_NAME', COUNT(*) 'DISTRICT_NUM' 
FROM ( SELECT A.AREA_NAME 
FROM NCLK.T_NCLK_EXAMROOM_LOG_HIS H, NCLK.T_NCLK_EXAMROOM E, NCLK.T_NCLK_ENDPOINT P, NCLK.T_NCLK_AREA A, 
NCLK.T_NCLK_AREA B, NCLK.T_NCLK_USER_ENDPOINT UP 
WHERE H.EXAMROOM_ID = E.EXAMROOM_ID AND E.ENDPOINT_ID = P.ENDPOINT_ID AND P.AREA_ID = A.AREA_ID AND 
A.PARENT_AREA_ID = B.AREA_ID AND E.ENDPOINT_ID = UP.ENDPOINT_ID AND UP.USER_ID = "137853b9b622410d95f4bb5a2be467ae" AND B.AREA_NAME = "镇江市" 
GROUP BY H.ERROR_TYPE, H.EXAMROOM_ID) HS
GROUP BY HS.AREA_NAME;

SELECT HS.AREA_NAME 'DISTRICT_NAME', COUNT(*) 'DISTRICT_NUM'
FROM ( SELECT A.AREA_NAME
FROM NCLK.T_NCLK_EXAMROOM_LOG_HIS H, NCLK.T_NCLK_EXAMROOM E, NCLK.T_NCLK_ENDPOINT P, NCLK.T_NCLK_AREA A,
NCLK.T_NCLK_AREA B, NCLK.T_NCLK_USER_ENDPOINT UP
WHERE H.EXAMROOM_ID = E.EXAMROOM_ID AND E.ENDPOINT_ID = P.ENDPOINT_ID AND P.AREA_ID = A.AREA_ID AND
A.PARENT_AREA_ID = B.AREA_ID AND E.ENDPOINT_ID = UP.ENDPOINT_ID AND UP.USER_ID = "137853b9b622410d95f4bb5a2be467ae" AND B.AREA_NAME = "南京市" 
AND H.ERROR_DATE > "2017-04-27 00:00"
GROUP BY H.ERROR_TYPE, H.EXAMROOM_ID) HS
GROUP BY HS.AREA_NAME;

SELECT HS.AREA_NAME 'DISTRICT_NAME', COUNT(*) 'DISTRICT_NUM', HS.ERROR_TYPE
FROM ( SELECT B.AREA_NAME, H.ERROR_TYPE
FROM NCLK.T_NCLK_EXAMROOM_LOG_HIS H, NCLK.T_NCLK_EXAMROOM E, NCLK.T_NCLK_ENDPOINT P, NCLK.T_NCLK_AREA A,  
NCLK.T_NCLK_AREA B, NCLK.T_NCLK_AREA C, NCLK.T_NCLK_USER_ENDPOINT UP 
WHERE H.EXAMROOM_ID = E.EXAMROOM_ID AND E.ENDPOINT_ID = P.ENDPOINT_ID AND P.AREA_ID = A.AREA_ID AND
A.PARENT_AREA_ID = B.AREA_ID AND E.ENDPOINT_ID = UP.ENDPOINT_ID AND A.STATE = 'A' AND B.STATE = 'A' AND  
C.STATE = 'A' AND P.STATE = 'A' AND UP.USER_ID = "137853b9b622410d95f4bb5a2be467ae" AND C.AREA_ID = "000000032" AND H.ERROR_DATE between "2017-01-01 00:00:00" and "2019-01-01 00:00:00" 
GROUP BY H.ERROR_TYPE, H.EXAMROOM_ID ) HS  
GROUP BY HS.AREA_NAME, H.ERROR_TYPE; 

-- O
select HS.AREA_NAME,
count(CASE WHEN HS.ERROR_TYPE='上报超时' THEN '上报超时' END) '上报超时',
count(CASE WHEN HS.ERROR_TYPE='时钟掉线' THEN '时钟掉线' END) '时钟掉线',
count(CASE WHEN HS.ERROR_TYPE='时间误差' THEN '时间误差' END) '时间误差'
FROM (SELECT A.AREA_NAME, H.ERROR_TYPE
FROM NCLK.T_NCLK_EXAMROOM_LOG_HIS H, NCLK.T_NCLK_EXAMROOM E, NCLK.T_NCLK_ENDPOINT P, NCLK.T_NCLK_AREA A,  
NCLK.T_NCLK_AREA B, NCLK.T_NCLK_AREA C, NCLK.T_NCLK_USER_ENDPOINT UP 
WHERE H.EXAMROOM_ID = E.EXAMROOM_ID AND E.ENDPOINT_ID = P.ENDPOINT_ID AND P.AREA_ID = A.AREA_ID AND
A.PARENT_AREA_ID = B.AREA_ID AND E.ENDPOINT_ID = UP.ENDPOINT_ID AND A.STATE = 'A' AND B.STATE = 'A' AND  
C.STATE = 'A' AND P.STATE = 'A' AND UP.USER_ID = "137853b9b622410d95f4bb5a2be467ae" AND B.AREA_ID = "3207" AND H.ERROR_DATE between "2017-01-01 00:00:00" and "2019-01-01 00:00:00" 
GROUP BY H.ERROR_TYPE, H.EXAMROOM_ID, B.AREA_NAME) HS
GROUP BY HS.AREA_NAME; 

-- X
SELECT HS.ENDPOINT_NAME, 
 count(CASE WHEN HS.ERROR_TYPE='上报超时' THEN '上报超时' END) '上报超时', 
 count(CASE WHEN HS.ERROR_TYPE='时钟掉线' THEN '时钟掉线' END) '时钟掉线', 
 count(CASE WHEN HS.ERROR_TYPE='时间误差' THEN '时间误差' END) '时间误差' 
 FROM ( SELECT P.ENDPOINT_NAME, H.ERROR_TYPE 
 FROM NCLK.T_NCLK_EXAMROOM_LOG_HIS H, NCLK.T_NCLK_EXAMROOM E, NCLK.T_NCLK_ENDPOINT P, NCLK.T_NCLK_AREA A, 
 NCLK.T_NCLK_AREA B, NCLK.T_NCLK_AREA C, NCLK.T_NCLK_USER_ENDPOINT UP 
 WHERE H.EXAMROOM_ID = E.EXAMROOM_ID AND E.ENDPOINT_ID = P.ENDPOINT_ID AND P.AREA_ID = A.AREA_ID AND 
 A.PARENT_AREA_ID = B.AREA_ID AND E.ENDPOINT_ID = UP.ENDPOINT_ID AND A.STATE = 'A' AND B.STATE = 'A' AND 
 C.STATE = 'A' AND P.STATE = 'A' AND UP.USER_ID = "137853b9b622410d95f4bb5a2be467ae" AND A.AREA_ID = "320705"
 GROUP BY H.ERROR_TYPE, H.EXAMROOM_ID, B.AREA_NAME) HS
GROUP BY HS.ENDPOINT_NAME; 

SELECT HS.AREA_NAME 'DISTRICT_NAME', COUNT(*) 'DISTRICT_NUM'
FROM (SELECT A.AREA_NAME
FROM NCLK.T_NCLK_EXAMROOM_LOG_HIS H, NCLK.T_NCLK_EXAMROOM E, NCLK.T_NCLK_ENDPOINT P, 
NCLK.T_NCLK_AREA A, NCLK.T_NCLK_AREA B, NCLK.T_NCLK_USER_ENDPOINT UP 
WHERE H.EXAMROOM_ID = E.EXAMROOM_ID AND E.ENDPOINT_ID = P.ENDPOINT_ID AND P.AREA_ID = A.AREA_ID 
AND A.PARENT_AREA_ID = B.AREA_ID AND E.ENDPOINT_ID = UP.ENDPOINT_ID AND A.STATE = 'A' AND B.STATE = 'A' AND P.STATE = 'A'
AND B.AREA_ID = "3201" AND UP.USER_ID = "137853b9b622410d95f4bb5a2be467ae"  AND H.ERROR_DATE between "2017-01-01 00:00:00" and "2019-01-01 00:00:00" 
GROUP BY H.ERROR_TYPE, H.EXAMROOM_ID) HS
GROUP BY HS.AREA_NAME;

SELECT HS.AREA_NAME 'DISTRICT_NAME', COUNT(*) 'DISTRICT_NUM'  
FROM ( SELECT A.AREA_NAME  
FROM NCLK.T_NCLK_EXAMROOM_LOG_HIS H, NCLK.T_NCLK_EXAMROOM E, NCLK.T_NCLK_ENDPOINT P, NCLK.T_NCLK_AREA A,  
NCLK.T_NCLK_AREA B, NCLK.T_NCLK_AREA C, NCLK.T_NCLK_USER_ENDPOINT UP 
WHERE H.EXAMROOM_ID = E.EXAMROOM_ID AND E.ENDPOINT_ID = P.ENDPOINT_ID AND P.AREA_ID = A.AREA_ID AND
A.PARENT_AREA_ID = B.AREA_ID AND E.ENDPOINT_ID = UP.ENDPOINT_ID AND A.STATE = 'A' AND B.STATE = 'A' AND  
C.STATE = 'A' AND P.STATE = 'A' AND UP.USER_ID = "137853b9b622410d95f4bb5a2be467ae" AND B.AREA_ID = "3201" AND H.ERROR_DATE between "2017-01-01 00:00:00" and "2019-01-01 00:00:00" 
GROUP BY H.ERROR_TYPE, H.EXAMROOM_ID ) HS  
GROUP BY HS.AREA_NAME; 

SELECT HS.ENDPOINT_NAME 'DISTRICT_NAME', COUNT(*) 'DISTRICT_NUM'  
FROM ( SELECT P.ENDPOINT_NAME  
FROM NCLK.T_NCLK_EXAMROOM_LOG_HIS H, NCLK.T_NCLK_EXAMROOM E, NCLK.T_NCLK_ENDPOINT P, NCLK.T_NCLK_AREA A,  
NCLK.T_NCLK_AREA B, NCLK.T_NCLK_AREA C, NCLK.T_NCLK_USER_ENDPOINT UP 
WHERE H.EXAMROOM_ID = E.EXAMROOM_ID AND E.ENDPOINT_ID = P.ENDPOINT_ID AND P.AREA_ID = A.AREA_ID AND
A.PARENT_AREA_ID = B.AREA_ID AND E.ENDPOINT_ID = UP.ENDPOINT_ID AND A.STATE = 'A' AND B.STATE = 'A' AND  
C.STATE = 'A' AND P.STATE = 'A' AND UP.USER_ID = "137853b9b622410d95f4bb5a2be467ae" 
AND A.AREA_ID = "320705" AND H.ERROR_DATE between "2017-01-01 00:00:00" and "2019-01-01 00:00:00" 
GROUP BY H.ERROR_TYPE, H.EXAMROOM_ID ) HS  
GROUP BY HS.ENDPOINT_NAME; 

SELECT P.ENDPOINT_NAME, HS.ERROR_TYPE, COUNT(*) 'ERROR_NUM' 
FROM ( SELECT H.ERROR_TYPE 
FROM NCLK.T_NCLK_EXAMROOM_LOG_HIS H, NCLK.T_NCLK_EXAMROOM E, NCLK.T_NCLK_ENDPOINT P, NCLK.T_NCLK_AREA A, 
NCLK.T_NCLK_USER_ENDPOINT UP 
WHERE H.EXAMROOM_ID = E.EXAMROOM_ID AND P.ENDPOINT_ID = E.ENDPOINT_ID AND P.AREA_ID = A.AREA_ID AND
E.ENDPOINT_ID = UP.ENDPOINT_ID AND A.STATE = 'A' AND P.STATE = 'A' AND UP.USER_ID = "137853b9b622410d95f4bb5a2be467ae" AND P.ENDPOINT_ID = "2200001011" 
GROUP BY H.ERROR_TYPE, E.EXAMROOM_ID ) HS 
GROUP BY P.ENDPOINT_NAME, HS.ERROR_TYPE;

SELECT HS.ERROR_TYPE, COUNT(*) 'ERROR_NUM' 
 FROM ( SELECT H.ERROR_TYPE 
 FROM NCLK.T_NCLK_EXAMROOM_LOG_HIS H, NCLK.T_NCLK_EXAMROOM E, NCLK.T_NCLK_ENDPOINT P, NCLK.T_NCLK_AREA A, 
 NCLK.T_NCLK_USER_ENDPOINT UP 
 WHERE H.EXAMROOM_ID = E.EXAMROOM_ID AND P.ENDPOINT_ID = E.ENDPOINT_ID AND P.AREA_ID = A.AREA_ID AND
 E.ENDPOINT_ID = UP.ENDPOINT_ID AND A.STATE = 'A' AND P.STATE = 'A' AND UP.USER_ID = "137853b9b622410d95f4bb5a2be467ae" AND P.ENDPOINT_ID = "2200001011"
 GROUP BY H.ERROR_TYPE, E.EXAMROOM_ID ) HS 
GROUP BY HS.ERROR_TYPE;

SELECT HS.ERROR_TYPE, COUNT(*) 'ERROR_NUM'  
FROM ( SELECT H.ERROR_TYPE  
FROM NCLK.T_NCLK_EXAMROOM_LOG_HIS H, NCLK.T_NCLK_EXAMROOM E, NCLK.T_NCLK_ENDPOINT P, NCLK.T_NCLK_AREA A,  
NCLK.T_NCLK_AREA B, NCLK.T_NCLK_USER_ENDPOINT UP  
WHERE H.EXAMROOM_ID = E.EXAMROOM_ID AND P.ENDPOINT_ID = E.ENDPOINT_ID AND P.AREA_ID = A.AREA_ID 
AND  A.PARENT_AREA_ID = B.AREA_ID AND E.ENDPOINT_ID = UP.ENDPOINT_ID AND A.STATE = 'A' AND B.STATE = 'A' 
AND  P.STATE = 'A' AND UP.USER_ID = "137853b9b622410d95f4bb5a2be467ae" AND B.AREA_ID = "3201"  
GROUP BY H.ERROR_TYPE, E.EXAMROOM_ID ) HS GROUP BY HS.ERROR_TYPE ;

SELECT H.ERROR_TYPE  , count(*)
FROM NCLK.T_NCLK_EXAMROOM_LOG_HIS H, NCLK.T_NCLK_EXAMROOM E, NCLK.T_NCLK_ENDPOINT P, NCLK.T_NCLK_AREA A,  
NCLK.T_NCLK_AREA B, NCLK.T_NCLK_USER_ENDPOINT UP  
WHERE H.EXAMROOM_ID = E.EXAMROOM_ID AND P.ENDPOINT_ID = E.ENDPOINT_ID AND P.AREA_ID = A.AREA_ID 
AND  A.PARENT_AREA_ID = B.AREA_ID AND E.ENDPOINT_ID = UP.ENDPOINT_ID AND A.STATE = 'A' AND B.STATE = 'A' 
AND  P.STATE = 'A' AND UP.USER_ID = "137853b9b622410d95f4bb5a2be467ae" AND B.AREA_ID = "3201"  
GROUP BY H.ERROR_TYPE, E.EXAMROOM_ID ;

-- test PIE
 SELECT HS.AREA_NAME 'DISTRICT_NAME', 
 count(CASE WHEN HS.ERROR_TYPE='上报超时' THEN '上报超时' END) '上报超时', 
 count(CASE WHEN HS.ERROR_TYPE='网络异常' THEN '网络异常' END) '网络异常',
 count(CASE WHEN HS.ERROR_TYPE='时间误差' THEN '时间误差' END) '时间误差' 
 FROM ( SELECT A.AREA_NAME, H.ERROR_TYPE 
 FROM NCLK.T_NCLK_EXAMROOM_LOG_HIS H, NCLK.T_NCLK_EXAMROOM E, NCLK.T_NCLK_ENDPOINT P, NCLK.T_NCLK_AREA A, 
 NCLK.T_NCLK_AREA B, NCLK.T_NCLK_AREA C, NCLK.T_NCLK_USER_ENDPOINT UP 
 WHERE H.EXAMROOM_ID = E.EXAMROOM_ID AND E.ENDPOINT_ID = P.ENDPOINT_ID AND P.AREA_ID = A.AREA_ID AND 
 A.PARENT_AREA_ID = B.AREA_ID AND B.PARENT_AREA_ID = C.AREA_ID AND E.ENDPOINT_ID = UP.ENDPOINT_ID AND 
 A.STATE = 'A' AND B.STATE = 'A' AND C.STATE = 'A' AND P.STATE = 'A' 
 AND UP.USER_ID = "137853b9b622410d95f4bb5a2be467ae" AND B.AREA_ID = "3201"
 GROUP BY H.ERROR_TYPE, H.EXAMROOM_ID, C.AR) HS
 GROUP BY HS.AREA_NAME;
 
 -- test TABLE
 SELECT HS.AREA_NAME 'DISTRICT_NAME', 
 count(CASE WHEN HS.ERROR_TYPE='上报超时' THEN '上报超时' END) '上报超时', 
 count(CASE WHEN HS.ERROR_TYPE='网络异常' THEN '网络异常' END) '网络异常',
 count(CASE WHEN HS.ERROR_TYPE='时间误差' THEN '时间误差' END) '时间误差' 
 FROM ( SELECT A.AREA_NAME, H.ERROR_TYPE 
 FROM NCLK.T_NCLK_EXAMROOM_LOG_HIS H, NCLK.T_NCLK_EXAMROOM E, NCLK.T_NCLK_ENDPOINT P, NCLK.T_NCLK_AREA A, 
 NCLK.T_NCLK_AREA B, NCLK.T_NCLK_AREA C, NCLK.T_NCLK_USER_ENDPOINT UP 
 WHERE H.EXAMROOM_ID = E.EXAMROOM_ID AND E.ENDPOINT_ID = P.ENDPOINT_ID AND P.AREA_ID = A.AREA_ID AND 
 A.PARENT_AREA_ID = B.AREA_ID AND B.PARENT_AREA_ID = C.AREA_ID AND E.ENDPOINT_ID = UP.ENDPOINT_ID AND 
 A.STATE = 'A' AND B.STATE = 'A' AND C.STATE = 'A' AND P.STATE = 'A' 
 AND UP.USER_ID = "137853b9b622410d95f4bb5a2be467ae" AND B.AREA_ID = "3201"
 GROUP BY H.ERROR_TYPE, H.EXAMROOM_ID, B.AREA_NAME) HS
 GROUP BY HS.AREA_NAME;

-- TEST->
SELECT B.AREA_NAME, H.ERROR_TYPE 
 FROM NCLK.T_NCLK_EXAMROOM_LOG_HIS H, NCLK.T_NCLK_EXAMROOM E, NCLK.T_NCLK_ENDPOINT P, NCLK.T_NCLK_AREA A, 
 NCLK.T_NCLK_AREA B, NCLK.T_NCLK_AREA C, NCLK.T_NCLK_USER_ENDPOINT UP 
 WHERE H.EXAMROOM_ID = E.EXAMROOM_ID AND E.ENDPOINT_ID = P.ENDPOINT_ID AND P.AREA_ID = A.AREA_ID AND 
 A.PARENT_AREA_ID = B.AREA_ID AND B.PARENT_AREA_ID = C.AREA_ID AND E.ENDPOINT_ID = UP.ENDPOINT_ID AND 
 A.STATE = 'A' AND B.STATE = 'A' AND C.STATE = 'A' AND P.STATE = 'A' 
 AND UP.USER_ID = "137853b9b622410d95f4bb5a2be467ae" AND C.AREA_ID = "000000032"
  GROUP BY H.ERROR_TYPE, H.EXAMROOM_ID;


